import { Inject, Injectable } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";
import { ROLE, type Role, JwtClaims } from "@rh/shared";
import { requireResortAccess, requireRoles, badRequest } from "../common/rbac";
import { round2 } from "../common/dates";
import { AuditService } from "../common/audit.service";
import { BookingsService } from "../bookings/bookings.service";
import { PermissionsService } from "../common/permissions";
import { NotificationsService } from "../notifications/notifications.service";
import { OptionsService } from "../options/options.service";
import { TaxService } from "../common/tax.service";

@Injectable()
export class PaymentsService {
  constructor(
    @Inject(PrismaService) private readonly prisma: PrismaService,
    @Inject(AuditService) private readonly audit: AuditService,
    @Inject(BookingsService) private readonly bookings: BookingsService,
    @Inject(NotificationsService) private readonly notifications: NotificationsService,
    @Inject(PermissionsService) private readonly perms: PermissionsService,
    @Inject(OptionsService) private readonly options: OptionsService,
    @Inject(TaxService) private readonly tax: TaxService,
  ) {}

  /**
   * Append to the payment ledger (doc §5.6) — never a single "Advance" column.
   * Recomputes booking.paymentState (UNPAID → PARTIAL → PAID).
   */
  async addPayment(
    claims: JwtClaims,
    bookingId: number,
    input: {
      amount: number;
      /** a code from this resort's own list — see methods.service.ts */
      method: string;
      type?: "ADVANCE" | "FINAL" | "REFUND";
      note?: string;
      /**
       * The identity of this write, generated by the device.
       *
       * A front desk that loses its connection queues the payment and replays
       * it later, and a replay often happens because the first attempt reached
       * the server and its response was lost coming back. Without this the
       * guest gets a second receipt. With it, the second arrival returns the
       * first payment and the booking as it now stands.
       */
      clientRef?: string;
    },
  ) {
    const b = await this.prisma.booking.findUnique({
      where: { id: bookingId },
      include: { payments: true },
    });
    if (!b || b.deletedAt) throw Object.assign(new Error("Booking not found"), { status: 404 });
    requireResortAccess(claims, b.resortId);
    await this.perms.require(claims, b.resortId, "payments.create");
    if (input.amount <= 0) throw badRequest("amount must be > 0");
    // the method has to be one this resort actually takes. `@IsEnum` used to
    // accept BKASH for a resort that has never taken bKash, because the enum
    // was global; the question is per resort, so the check is too.
    await this.options.assertAccepted(b.resortId, "PAYMENT_METHOD", input.method);
    if (b.state === "CANCELLED" && input.type !== "REFUND") {
      throw badRequest("Cancelled bookings accept refunds only");
    }

    const type =
      input.type ??
      (b.payments.length === 0 && b.paymentState === "UNPAID" ? "ADVANCE" : "FINAL");

    // a replay is answered with the original, never with a second receipt
    if (input.clientRef) {
      const existing = await this.prisma.payment.findUnique({
        where: { bookingId_clientRef: { bookingId, clientRef: input.clientRef } },
      });
      if (existing) {
        return {
          payment: { ...existing, amount: Number(existing.amount) },
          booking: await this.bookings.detail(claims, bookingId),
          replayed: true,
        };
      }
    }

    const payment = await this.prisma.$transaction(async (tx) => {
      const created = await tx.payment.create({
        data: {
          bookingId,
          amount: input.amount as never,
          method: input.method,
          paymentType: type,
          receivedById: claims.userId,
          note: input.note,
          clientRef: input.clientRef,
        },
      });

      const paid = b.payments
        .filter((p) => p.paymentType !== "REFUND")
        .reduce((s, p) => s + Number(p.amount), 0);
      void paid;
      await this.audit.log(
        {
          actorId: claims.userId,
          resortId: b.resortId,
          action: `payment.${type.toLowerCase()}`,
          entity: "booking",
          entityId: bookingId,
          diff: { amount: input.amount, method: input.method },
        },
        tx,
      );
      return created;
    });

    const detail = await this.bookings.detail(claims, bookingId); // recompute + persist state
    if (input.type !== "REFUND") {
      await this.notifications.notifyPayment(bookingId, Number(payment.amount), input.method);
    }
    return { payment: { ...payment, amount: Number(payment.amount) }, booking: detail, replayed: false };
  }

  /**
   * Outstanding dues across a resort (doc §3.6), told apart by who owes them.
   *
   * A guest's balance and an agency's balance are one number here and two
   * different jobs everywhere else. The guest's is collected at the desk on
   * the morning they leave, in cash or bKash, by whoever is standing there.
   * The agency's is a trade account: the room was sold on the agency's paper,
   * the money arrives when the two businesses settle, and any one booking is a
   * line in that settlement — not something to ask a departing guest for.
   *
   * Totalled together, the red number at the top of the screen was one nobody
   * could act on, and the desk read a guest's name beside money that guest
   * does not owe. The rows carry who is behind each debt, the totals are
   * struck separately, and the agency side is also added up per agency —
   * because "who do I ring, and for how much" is a question about an agency,
   * not about a booking.
   */
  async dues(claims: JwtClaims, resortId: number) {
    requireResortAccess(claims, resortId);
    // the matrix showed this box and nothing asked for it: hiding the menu
    // link is not access control, and a token plus curl was the whole gap
    await this.perms.require(claims, resortId, "payments.view");
    const taxRules = await this.tax.rulesFor(resortId);
    const bookings = await this.prisma.booking.findMany({
      where: { resortId, deletedAt: null, state: { in: ["CONFIRMED", "CHECKED_IN", "CHECKED_OUT"] } },
      include: {
        payments: true,
        guest: { select: { fullName: true, phone: true } },
        items: true,
        /**
         * Who sold it, and which agency they sell for. Agency staff hold no
         * account of their own — they hang off the agency's owner — so the
         * account is theirs or their parent's, the same rule the agent report
         * uses.
         */
        agentUser: {
          select: {
            id: true,
            name: true,
            accountId: true,
            parentAgent: { select: { accountId: true } },
          },
        },
      },
      orderBy: { checkIn: "asc" },
    });

    const owing = bookings
      .map((b) => ({ b, t: BookingsService.computeTotals(b, taxRules) }))
      .filter(({ t }) => t.due > 0.001);

    // one query for the names, rather than one per booking
    const accountIds = [
      ...new Set(
        owing
          .map(({ b }) => b.agentUser?.accountId ?? b.agentUser?.parentAgent?.accountId)
          .filter((id): id is number => id != null),
      ),
    ];
    // an account is a `tenants` row — the agency itself, not one of its people
    const accounts = accountIds.length
      ? await this.prisma.tenant.findMany({
          where: { id: { in: accountIds } },
          select: { id: true, name: true },
        })
      : [];
    const agencyName = new Map<number, string>(accounts.map((a) => [a.id, a.name]));

    const rows = owing.map(({ b, t }) => {
      const accountId = b.agentUser?.accountId ?? b.agentUser?.parentAgent?.accountId ?? null;
      return {
        id: b.id,
        code: b.code,
        state: b.state,
        guest: b.guest,
        checkIn: b.checkIn,
        checkOut: b.checkOut,
        rooms: b.items.map((i) => i.roomId).length,
        /**
         * Null for a booking the resort took itself — a walk-in, a phone call,
         * its own website. That null is the whole distinction the screen draws.
         */
        agent: b.agentUser
          ? {
              id: b.agentUser.id,
              name: b.agentUser.name,
              accountId,
              // a lone agent with no agency behind them is named by themselves
              agency: (accountId != null ? agencyName.get(accountId) : null) ?? b.agentUser.name,
            }
          : null,
        ...t,
      };
    });

    const guestRows = rows.filter((r) => r.agent === null);
    const agencyRows = rows.filter((r) => r.agent !== null);

    /** What each agency owes across every booking of theirs that is short. */
    const byAgency = [
      ...agencyRows
        .reduce((map, r) => {
          // an agency's staff all settle through the agency; an agent with no
          // account is their own debtor, keyed on themselves
          const key = r.agent!.accountId != null ? `a${r.agent!.accountId}` : `u${r.agent!.id}`;
          const at = map.get(key) ?? {
            accountId: r.agent!.accountId,
            agency: r.agent!.agency,
            bookings: 0,
            due: 0,
          };
          at.bookings++;
          at.due += r.due;
          map.set(key, at);
          return map;
        }, new Map<string, { accountId: number | null; agency: string; bookings: number; due: number }>())
        .values(),
    ]
      .map((a) => ({ ...a, due: round2(a.due) }))
      .sort((a, b) => b.due - a.due);

    const sum = (list: typeof rows) => round2(list.reduce((s, r) => s + r.due, 0));
    return {
      total: sum(rows),
      count: rows.length,
      guestTotal: sum(guestRows),
      guestCount: guestRows.length,
      agencyTotal: sum(agencyRows),
      agencyCount: agencyRows.length,
      byAgency,
      rows,
    };
  }
}
