-- A resort has one live subscription.
--
-- `setSubscription` created a new row in TRIAL on every call and never
-- cancelled the old one, and nothing in the schema stopped it. So a plan change
-- restarted the free trial — a way to never pay — and once the second trial
-- ended the monthly sweep, which walks every ACTIVE and PAST_DUE subscription,
-- invoiced the resort twice. MRR counted both.
--
-- The rule is enforced by a column the application cannot write. `liveKey` is
-- generated by the database — the resort id while the status is live, NULL once
-- it is cancelled — and carries the unique index. MySQL and MariaDB both allow
-- many NULLs in a unique index, so the history stays and only the live row is
-- unique. A column the application maintains is one it can forget to maintain,
-- and this rule is worth more than that.

-- Existing data first: the index cannot be added over duplicates. Where a
-- resort has more than one live row the newest wins — it is the one
-- `PlanLimitsService` already picked (findFirst, id desc), so nobody's limits
-- move — and the rest are marked superseded.
UPDATE `subscriptions` s
LEFT JOIN (
  SELECT `resortId`, MAX(`id`) AS `keep`
  FROM `subscriptions`
  WHERE `status` IN ('TRIAL', 'ACTIVE', 'PAST_DUE')
  GROUP BY `resortId`
) newest ON newest.`resortId` = s.`resortId` AND newest.`keep` = s.`id`
SET s.`status` = 'CANCELLED',
    s.`cancelledAt` = COALESCE(s.`cancelledAt`, CURRENT_TIMESTAMP(3))
WHERE s.`status` IN ('TRIAL', 'ACTIVE', 'PAST_DUE') AND newest.`keep` IS NULL;

-- VIRTUAL rather than STORED: a stored generated column forces a table rebuild,
-- and rebuilding a table this many foreign keys point at fails with 1215. A
-- virtual one is computed on read, can still carry a unique index on both MySQL
-- and MariaDB, and costs nothing here.
ALTER TABLE `subscriptions`
  ADD COLUMN `liveKey` INTEGER
  GENERATED ALWAYS AS (
    CASE WHEN `status` IN ('TRIAL', 'ACTIVE', 'PAST_DUE') THEN `resortId` ELSE NULL END
  ) VIRTUAL;

CREATE UNIQUE INDEX `subscriptions_liveKey_key` ON `subscriptions`(`liveKey`);
