/**
 * Build a signed release APK, and record that it happened.
 *
 * The last mobile app in this repository had eight screens, type-checked
 * cleanly, and was never built once — so the build is a committed script with
 * a receipt, not a command somebody remembers. Run: `pnpm -F @rh/mobile build:apk`.
 *
 * Three things it sets up that `expo prebuild` leaves undone:
 *
 *  - `local.properties`, so Gradle can find the Android SDK.
 *  - A real release keystore. Expo's template signs release builds with the
 *    *debug* key, which installs fine and then cannot be updated by a properly
 *    signed build: Android refuses an update whose signature changed, so every
 *    phone would need an uninstall, losing its session. Better to be right from
 *    the first APK anyone receives.
 *  - The Gradle signing config that uses it.
 *
 * The keystore lives outside the repository, under the user's home directory.
 * In the repository it would be one `git clean -fdx` away from gone, and
 * losing it means never being able to update this app on any phone that has it.
 */
import { execFileSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const MOBILE = join(HERE, "..");
const ANDROID = join(MOBILE, "android");

const KEY_DIR = join(homedir(), ".resortmela", "android");
const KEYSTORE = join(KEY_DIR, "resortmela-release.keystore");
const KEY_PROPS = join(KEY_DIR, "keystore.properties");
const ALIAS = "resortmela";

const say = (m) => console.log(`\n### ${m}`);
const posix = (p) => p.replace(/\\/g, "/");

// ---------------------------------------------------------------- the SDK

function androidSdk() {
  const candidates = [
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    join(process.env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"), "Android", "Sdk"),
    join(homedir(), "Library", "Android", "sdk"),
    join(homedir(), "Android", "Sdk"),
  ].filter(Boolean);
  const found = candidates.find((dir) => existsSync(join(dir, "platform-tools")));
  if (!found) {
    throw new Error(
      `No Android SDK found. Looked in:\n  ${candidates.join("\n  ")}\n` +
        "Install it, or set ANDROID_HOME.",
    );
  }
  return found;
}

// ------------------------------------------------------------ the keystore

/**
 * `keytool` ships with the JDK but is not always on PATH — on Windows the
 * Oracle launcher directory puts `java` there and nothing else.
 */
function keytool() {
  const exe = process.platform === "win32" ? "keytool.exe" : "keytool";
  const home = process.env.JAVA_HOME;
  if (home && existsSync(join(home, "bin", exe))) return join(home, "bin", exe);
  return exe; // on PATH, or the error will say so plainly
}

function ensureKeystore() {
  if (existsSync(KEYSTORE) && existsSync(KEY_PROPS)) {
    return Object.fromEntries(
      readFileSync(KEY_PROPS, "utf8")
        .split("\n")
        .filter((l) => l.includes("="))
        .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
    );
  }

  say("creating a release keystore (first build only)");
  mkdirSync(KEY_DIR, { recursive: true });
  // base64url: no shell-hostile characters, and never echoed to a terminal
  const password = randomBytes(24).toString("base64url");

  execFileSync(
    keytool(),
    [
      "-genkeypair", "-v",
      "-storetype", "PKCS12",
      "-keystore", KEYSTORE,
      "-alias", ALIAS,
      "-keyalg", "RSA",
      "-keysize", "2048",
      // 10000 days: Play requires a key valid well past any plausible release
      "-validity", "10000",
      // `:env`, not the value: an argument is visible in the process list and
      // in any stack trace the command prints on the way out
      "-storepass:env", "RM_KEYSTORE_PASSWORD",
      "-keypass:env", "RM_KEYSTORE_PASSWORD",
      "-dname", "CN=Resort Mela, OU=Platform, O=Resort Mela, L=Dhaka, C=BD",
    ],
    { stdio: "inherit", env: { ...process.env, RM_KEYSTORE_PASSWORD: password } },
  );

  writeFileSync(
    KEY_PROPS,
    [
      "# Generated by scripts/build-apk.mjs. Back this directory up.",
      "# Without it, no future build can update an installed Resort Mela.",
      `storeFile=${posix(KEYSTORE)}`,
      `storePassword=${password}`,
      `keyAlias=${ALIAS}`,
      `keyPassword=${password}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );

  console.log(`\n  !! Keystore written to ${KEYSTORE}`);
  console.log("  !! Back up that folder. Losing it means this app can never be updated again.\n");
  return ensureKeystore();
}

// ------------------------------------------------------------- the project

/**
 * `android/` is generated and git-ignored, so a fresh clone has none. Building
 * it here rather than asking the operator to remember `expo prebuild` keeps
 * the one-command promise: check out the repo, run this, get an APK.
 */
function ensureNativeProject() {
  if (existsSync(join(ANDROID, "gradlew.bat")) || existsSync(join(ANDROID, "gradlew"))) return;
  say("expo prebuild (no android/ directory yet)");
  execFileSync("npx", ["expo", "prebuild", "--platform", "android", "--no-install"], {
    cwd: MOBILE,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
}

// -------------------------------------------------------------- the gradle

function configureGradle(sdk, key) {
  writeFileSync(join(ANDROID, "local.properties"), `sdk.dir=${posix(sdk)}\n`);

  const buildGradle = join(ANDROID, "app", "build.gradle");
  let text = readFileSync(buildGradle, "utf8");
  if (text.includes("RESORTMELA_STORE_FILE")) return; // already patched

  // a signingConfig beside the template's `debug` one, reading the properties
  // written above — the passwords never enter the repository or a build log
  text = text.replace(
    /( {8}debug \{\n(?: {12}.*\n)+ {8}\}\n)/,
    `$1        release {
            storeFile file(project.property('RESORTMELA_STORE_FILE'))
            storePassword project.property('RESORTMELA_STORE_PASSWORD')
            keyAlias project.property('RESORTMELA_KEY_ALIAS')
            keyPassword project.property('RESORTMELA_KEY_PASSWORD')
        }\n`,
  );
  text = text.replace(
    /( {8}release \{\n(?: {12}\/\/.*\n)*) {12}signingConfig signingConfigs\.debug/,
    "$1            signingConfig signingConfigs.release",
  );
  if (!text.includes("signingConfigs.release")) {
    throw new Error("Could not patch android/app/build.gradle — its shape changed. Patch it by hand.");
  }
  writeFileSync(buildGradle, text);

  const props = join(ANDROID, "gradle.properties");
  appendFileSync(
    props,
    [
      "",
      "# Release signing. Written by scripts/build-apk.mjs; not committed.",
      `RESORTMELA_STORE_FILE=${key.storeFile}`,
      `RESORTMELA_STORE_PASSWORD=${key.storePassword}`,
      `RESORTMELA_KEY_ALIAS=${key.keyAlias}`,
      `RESORTMELA_KEY_PASSWORD=${key.keyPassword}`,
      "",
    ].join("\n"),
  );
}

// --------------------------------------------------------------- the build

function build(sdk) {
  say("gradle assembleRelease");
  // absolute: with `shell` on Windows the working directory is not searched,
  // so a bare `gradlew.bat` is simply not found
  const gradlew = join(ANDROID, process.platform === "win32" ? "gradlew.bat" : "gradlew");
  execFileSync(`"${gradlew}"`, ["assembleRelease", "--no-daemon"], {
    cwd: ANDROID,
    stdio: "inherit",
    env: { ...process.env, ANDROID_HOME: sdk, ANDROID_SDK_ROOT: sdk },
    shell: true,
  });
}

// ------------------------------------------------------------- the receipt

function receipt() {
  const apk = join(ANDROID, "app", "build", "outputs", "apk", "release", "app-release.apk");
  if (!existsSync(apk)) throw new Error(`Gradle reported success but ${apk} is not there.`);

  const bytes = readFileSync(apk);
  const sha = createHash("sha256").update(bytes).digest("hex");
  const size = (statSync(apk).size / 1024 / 1024).toFixed(1);
  const { version } = JSON.parse(readFileSync(join(MOBILE, "app.json"), "utf8")).expo;
  const today = new Date().toISOString().slice(0, 10);

  const file = join(MOBILE, "RELEASES.md");
  if (!existsSync(file)) {
    writeFileSync(
      file,
      [
        "# Builds",
        "",
        "Every APK this repository has actually produced, appended by",
        "`scripts/build-apk.mjs`. An empty table means the app has been written",
        "but never built — the state the previous mobile app died in, and what",
        "`the-mobile-app-is-real.spec.ts` exists to catch.",
        "",
        "| Version | Date | Size | SHA-256 |",
        "|---|---|---|---|",
        "",
      ].join("\n"),
    );
  }
  appendFileSync(file, `| ${version} | ${today} | ${size} MB | sha256:${sha} |\n`);

  console.log(`\n  APK      ${apk}`);
  console.log(`  Version  ${version}`);
  console.log(`  Size     ${size} MB`);
  console.log(`  SHA-256  ${sha}`);
  console.log(`\n  Install: adb install -r "${apk}"\n`);
}

const sdk = androidSdk();
say(`Android SDK: ${sdk}`);
ensureNativeProject();
configureGradle(sdk, ensureKeystore());
build(sdk);
receipt();
